apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  labels:
    app: laravel
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: ${{ secrets.DOCKER_USERNAME }}/laravel-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          value: "rds-endpoint"
        - name: DB_DATABASE
          value: "laravel"
        - name: DB_USERNAME
          value: "user"
        - name: DB_PASSWORD
          value: "password"
