name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Files (Debugging Step)
        run: ls -l  # ✅ This checks if Dockerfile exists

      - name: List Files Inside `modules/` (Debugging Step)
        run: ls -l modules  # ✅ Ensure Dockerfile is inside `modules/`
        
     
